ersion: "3"

services:
  ttt:
    image: ttt_api
    container_name: ttt_api
    restart: always
    networks:
      - web
    labels:
      - "traefik.backend=ttt"
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:ttt.langcab.com;PathPrefixStrip:/api"

networks:
  web:
    external: true